id: P007094
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD14767
  title: སྨན་མདོ་དང་འོད་མདོ།
  author: ''
  volumes:
    144d8d4f8e244367baed5500bdb5a811:
      image_group_id: I4PD952
      title: ''
      volume_number: 1
      total_pages: 238
ebook_metadata:
  title: སྨན་མདོ་དང་འོད་མདོ།
  author: ''
  sku: P007094
  cover: cover.jpg
  layers:
  - pagination
