id: P007094
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2PD14767
  title: སྨན་མདོ་དང་འོད་མདོ།
  author: ''
  volumes:
    4af6a887c6bb4c7ba3733f1b58eae748:
      image_group_id: I4PD952
      title: Volume 1 of sman mdo dang 'od mdo/
      volume_number: 1
      total_pages: 238
      base_file: v001.txt
