id: I7030ABB0
legacy_id: P007094
ocr_import_info:
  bdrc_scan_id: W2PD14767
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T05:21:10'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T09:18:18.345826+00:00'
last_modified: 2022-09-03 17:18:40.100429
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD14767
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2PD14767
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྨན་མདོ་དང་འོད་མདོ།
statistics:
  ocr_word_mean_confidence_index: 0.6564749494644143
  ocr_word_median_confidence_index: 0.699999988079071
quality: null
bases:
  I4PD952:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD952
      total_pages: 238
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD952.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6564749494644143
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
